version: '3'

services:
   redis:
      build:
        context: './redis/'
        args:
          REDIS_VERSION: ${REDIS_VERSION}
      ports:
        - "6379:6379"
      container_name: "${REDIS_NAME}"

